### PR TITLE
(Go version) Multi platform build

### PR DESCRIPTION
**Pull request by MaxHorstmann**
As a precursor to adding a release workflow (https://github.com/StackExchange/blackbox/pull/318): build Linux, Windows, and Darwin binaries. Inspired by [dnscontrol](https://github.com/StackExchange/dnscontrol/blob/master/build/build.go).

### CODE REVIEW

**Comment by MaxHorstmann** [comment]
@tlimoncelli mind taking a look? Note that building the Windows version currently fails: https://github.com/StackExchange/blackbox/issues/320

**Comment by tlimoncelli** [comment]
I've never tried building this on Windows but I'll sent a PR that fixes the immediate problem.  The tests definitely won't run and will require a bigger project.

**Comment by MaxHorstmann** [comment]
Would you see value in providing a Windows binary? Seems to me that this could be useful and one of the benefits of the Go port.

**Comment by tlimoncelli** [comment]
Merge in these changes to get a working Windows build.  NB: the tests won't work, but it will compile.  https://github.com/StackExchange/blackbox/pull/321

**Comment by MaxHorstmann** [comment]
@tlimoncelli I just added a branch protection rule for the `master` branch, identical to the one we added to dnscontrol. So- can I get an approval for this PR please?

**Review by tlimoncelli — APPROVED** [review]

**Pull request merged**
