### PR TITLE
Fix change_to_vcs_root in issue #105

### PR DESCRIPTION
**Pull request by selfcommit**
Resolution to breaking of blackbox_initialize

### CODE REVIEW

**Comment by tlimoncelli** [comment]
After making this change, "make confidence" still fails.
The "make confidence" test started failing as of:

a648fb8e46e2b2dea8133c246d9157757f70f6ca is the first bad commit
commit a648fb8e46e2b2dea8133c246d9157757f70f6ca
Author: Dan OBoyle <Dan@stackoverflow.com>
Date:   Sun Jun 28 19:26:47 2015 -0400

    Added / Pruned quotes and separated local variable declaration from assignment.

Since that's your commit, could you investigate?

**Comment by selfcommit** [comment]
Having a look...

**Comment by selfcommit** [comment]
@TomOnTime  I can confirm the confidence test is good now.  I attempted to rebase out the Bob user from my last commit, but it looks like github wants to remember him.

**Comment by TomOnTime** [comment]
LGTM

**Pull request merged**
