### PR TITLE
Fixes issue were .gitignore is not included in the commit when you register new file

### PR DESCRIPTION
**Pull request by diclophis**

### CODE REVIEW

**Comment by tlimoncelli** [comment]
I only see 2 files changed. Is something missing?

**Comment by diclophis** [comment]
Oh, I just had alot of commits getting to this change, i will rebase this pr to clean it up

**Comment by tlimoncelli** [comment]
This seems related to https://github.com/StackExchange/blackbox/pull/207

Would you two please confer about what to do?

**Comment by diclophis** [comment]
@tlimoncelli we would like to proceed with this PR and close #207 

Please let me know if there is anything else blocking this PR.

Thanks

**Comment by tlimoncelli** [comment]
Thanks for submitting this!  Sorry for the delay.

**Pull request merged**
